/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import TDA.Cola;
import TDA.Lista;
import edaproyecto.Expediente;
import edaproyecto.dependencias;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sebga
 */
public class MostrarTRA extends javax.swing.JFrame {

    /**
     * Creates new form MostrarTRA
     */
    private DefaultTableModel modelo;
    private Image icon;
    public MostrarTRA() {
    }
    
    public MostrarTRA(Lista<dependencias> Listadep) {
        setLocationRelativeTo(null);
        initComponents();
        icon = new ImageIcon(getClass().getResource("/imagenes/logo2_1.png")).getImage();
        setIconImage(icon);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        modelo = new DefaultTableModel();
       
        modelo.addColumn("ID");
        modelo.addColumn("PRIORIDAD");
        modelo.addColumn("DNI");
        modelo.addColumn("NOMBRES");
        modelo.addColumn("Celular");
        modelo.addColumn("EMAIL");
        modelo.addColumn("ASUNTO");
        modelo.addColumn("FECHAINICIO");
        modelo.addColumn("DOCUMENTOREF");
        modelo.addColumn("TIPO");
        modelo.addColumn("DEPENDENCIA");
        this.jTable1.setModel(modelo);
        mostrartabla(Listadep);
        jTable1.setDefaultEditor(Object.class, null);
    }
    public void mostrartabla(Lista<dependencias> Listadep){
        Cola<Expediente> aux1 = new Cola();
        for (int i =1 ; i <=Listadep.longitud(); i++) {
            while (!Listadep.iesimo(i).getColaexp().esVacia()){
            Expediente aux = Listadep.iesimo(i).getColaexp().desencolar();
            String[] fila = new String[11];
            fila[0] = String.valueOf(aux.getId());
            fila[1] = String.valueOf(aux.getPrioridad());
            fila[2] = String.valueOf(aux.getDni());
            fila[3] = String.valueOf(aux.getNombres());
            fila[4] = String.valueOf(aux.getCelular());
            fila[5] = String.valueOf(aux.getEmail());
            fila[6] = String.valueOf(aux.getAsunto());
            fila[7] = String.valueOf(aux.getFechaInicio());
            fila[8] = String.valueOf(aux.getDocumentoReferencia());
            if (aux.getInterno()){
                fila[9]="Interno";
            }
            else {
                fila[9]="Externo";
            }
                if (!aux.getSeguimiento().esVacia()) {
                   fila[10]=String.valueOf(aux.getSeguimiento().getUltimo().getItem().getNombre()); 
                } else {
                    fila[10]="No";
                }
            
            modelo.addRow(fila);
            aux1.encolar(aux);
            }
            Listadep.iesimo(i).setColaexp(aux1);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MostrarTRA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MostrarTRA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MostrarTRA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MostrarTRA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MostrarTRA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
